// Code generated by MockGen. DO NOT EDIT.
// Source: photogallery/internal/upload/events (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -destination=events_mock.go -package=mocks photogallery/internal/upload/events Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	events "photogallery/internal/upload/events"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// PublishPhoto mocks base method.
func (m *MockNotifier) PublishPhoto(ctx context.Context, event *events.UploadEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishPhoto", ctx, event)
}

// PublishPhoto indicates an expected call of PublishPhoto.
func (mr *MockNotifierMockRecorder) PublishPhoto(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPhoto", reflect.TypeOf((*MockNotifier)(nil).PublishPhoto), ctx, event)
}
