// Code generated by MockGen. DO NOT EDIT.
// Source: photogallery/gen/gallery (interfaces: GalleryServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=gallery_client_mock.go -package=mocks photogallery/gen/gallery GalleryServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gallery "photogallery/gen/gallery"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGalleryServiceClient is a mock of GalleryServiceClient interface.
type MockGalleryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockGalleryServiceClientMockRecorder
	isgomock struct{}
}

// MockGalleryServiceClientMockRecorder is the mock recorder for MockGalleryServiceClient.
type MockGalleryServiceClientMockRecorder struct {
	mock *MockGalleryServiceClient
}

// NewMockGalleryServiceClient creates a new mock instance.
func NewMockGalleryServiceClient(ctrl *gomock.Controller) *MockGalleryServiceClient {
	mock := &MockGalleryServiceClient{ctrl: ctrl}
	mock.recorder = &MockGalleryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGalleryServiceClient) EXPECT() *MockGalleryServiceClientMockRecorder {
	return m.recorder
}

// CloseGallery mocks base method.
func (m *MockGalleryServiceClient) CloseGallery(ctx context.Context, in *gallery.CloseGalleryRequest, opts ...grpc.CallOption) (*gallery.CloseGalleryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CloseGallery", varargs...)
	ret0, _ := ret[0].(*gallery.CloseGalleryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseGallery indicates an expected call of CloseGallery.
func (mr *MockGalleryServiceClientMockRecorder) CloseGallery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseGallery", reflect.TypeOf((*MockGalleryServiceClient)(nil).CloseGallery), varargs...)
}

// CreateGallery mocks base method.
func (m *MockGalleryServiceClient) CreateGallery(ctx context.Context, in *gallery.CreateGalleryRequest, opts ...grpc.CallOption) (*gallery.Gallery, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateGallery", varargs...)
	ret0, _ := ret[0].(*gallery.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGallery indicates an expected call of CreateGallery.
func (mr *MockGalleryServiceClientMockRecorder) CreateGallery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGallery", reflect.TypeOf((*MockGalleryServiceClient)(nil).CreateGallery), varargs...)
}

// GetGallery mocks base method.
func (m *MockGalleryServiceClient) GetGallery(ctx context.Context, in *gallery.GetGalleryRequest, opts ...grpc.CallOption) (*gallery.Gallery, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGallery", varargs...)
	ret0, _ := ret[0].(*gallery.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGallery indicates an expected call of GetGallery.
func (mr *MockGalleryServiceClientMockRecorder) GetGallery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGallery", reflect.TypeOf((*MockGalleryServiceClient)(nil).GetGallery), varargs...)
}

// IsMember mocks base method.
func (m *MockGalleryServiceClient) IsMember(ctx context.Context, in *gallery.IsMemberRequest, opts ...grpc.CallOption) (*gallery.IsMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsMember", varargs...)
	ret0, _ := ret[0].(*gallery.IsMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockGalleryServiceClientMockRecorder) IsMember(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockGalleryServiceClient)(nil).IsMember), varargs...)
}

// JoinGallery mocks base method.
func (m *MockGalleryServiceClient) JoinGallery(ctx context.Context, in *gallery.JoinGalleryRequest, opts ...grpc.CallOption) (*gallery.JoinGalleryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "JoinGallery", varargs...)
	ret0, _ := ret[0].(*gallery.JoinGalleryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinGallery indicates an expected call of JoinGallery.
func (mr *MockGalleryServiceClientMockRecorder) JoinGallery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGallery", reflect.TypeOf((*MockGalleryServiceClient)(nil).JoinGallery), varargs...)
}

// LeaveGallery mocks base method.
func (m *MockGalleryServiceClient) LeaveGallery(ctx context.Context, in *gallery.LeaveGalleryRequest, opts ...grpc.CallOption) (*gallery.LeaveGalleryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LeaveGallery", varargs...)
	ret0, _ := ret[0].(*gallery.LeaveGalleryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaveGallery indicates an expected call of LeaveGallery.
func (mr *MockGalleryServiceClientMockRecorder) LeaveGallery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveGallery", reflect.TypeOf((*MockGalleryServiceClient)(nil).LeaveGallery), varargs...)
}

// ListGalleries mocks base method.
func (m *MockGalleryServiceClient) ListGalleries(ctx context.Context, in *gallery.ListGalleriesRequest, opts ...grpc.CallOption) (*gallery.ListGalleriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGalleries", varargs...)
	ret0, _ := ret[0].(*gallery.ListGalleriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGalleries indicates an expected call of ListGalleries.
func (mr *MockGalleryServiceClientMockRecorder) ListGalleries(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleries", reflect.TypeOf((*MockGalleryServiceClient)(nil).ListGalleries), varargs...)
}

// ListGalleriesByMember mocks base method.
func (m *MockGalleryServiceClient) ListGalleriesByMember(ctx context.Context, in *gallery.ListGalleriesByMemberRequest, opts ...grpc.CallOption) (*gallery.ListGalleriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGalleriesByMember", varargs...)
	ret0, _ := ret[0].(*gallery.ListGalleriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGalleriesByMember indicates an expected call of ListGalleriesByMember.
func (mr *MockGalleryServiceClientMockRecorder) ListGalleriesByMember(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleriesByMember", reflect.TypeOf((*MockGalleryServiceClient)(nil).ListGalleriesByMember), varargs...)
}

// ListMembers mocks base method.
func (m *MockGalleryServiceClient) ListMembers(ctx context.Context, in *gallery.ListMembersRequest, opts ...grpc.CallOption) (*gallery.ListMembersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMembers", varargs...)
	ret0, _ := ret[0].(*gallery.ListMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockGalleryServiceClientMockRecorder) ListMembers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockGalleryServiceClient)(nil).ListMembers), varargs...)
}

// SendModeratorAlert mocks base method.
func (m *MockGalleryServiceClient) SendModeratorAlert(ctx context.Context, in *gallery.SendModeratorAlertRequest, opts ...grpc.CallOption) (*gallery.SendModeratorAlertResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendModeratorAlert", varargs...)
	ret0, _ := ret[0].(*gallery.SendModeratorAlertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendModeratorAlert indicates an expected call of SendModeratorAlert.
func (mr *MockGalleryServiceClientMockRecorder) SendModeratorAlert(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendModeratorAlert", reflect.TypeOf((*MockGalleryServiceClient)(nil).SendModeratorAlert), varargs...)
}
