// Code generated by MockGen. DO NOT EDIT.
// Source: photogallery/internal/upload (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock.go -package=mocks photogallery/internal/upload Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "photogallery/internal/upload/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, photoID uuid.UUID) (*model.Record, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, photoID)
	ret0, _ := ret[0].(*model.Record)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, photoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, photoID)
}

// ListByGallery mocks base method.
func (m *MockRepository) ListByGallery(ctx context.Context, galleryID uuid.UUID, offset, limit int) ([]*model.Record, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGallery", ctx, galleryID, offset, limit)
	ret0, _ := ret[0].([]*model.Record)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByGallery indicates an expected call of ListByGallery.
func (mr *MockRepositoryMockRecorder) ListByGallery(ctx, galleryID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGallery", reflect.TypeOf((*MockRepository)(nil).ListByGallery), ctx, galleryID, offset, limit)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, rec *model.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, rec)
}
