// Code generated by MockGen. DO NOT EDIT.
// Source: ../api/grpc.go
//
// Generated by this command:
//
//	mockgen -source=../api/grpc.go -destination=upload_stream_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	upload "photogallery/gen/upload"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuploadStream is a mock of uploadStream interface.
type MockuploadStream struct {
	ctrl     *gomock.Controller
	recorder *MockuploadStreamMockRecorder
	isgomock struct{}
}

// MockuploadStreamMockRecorder is the mock recorder for MockuploadStream.
type MockuploadStreamMockRecorder struct {
	mock *MockuploadStream
}

// NewMockuploadStream creates a new mock instance.
func NewMockuploadStream(ctrl *gomock.Controller) *MockuploadStream {
	mock := &MockuploadStream{ctrl: ctrl}
	mock.recorder = &MockuploadStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuploadStream) EXPECT() *MockuploadStreamMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockuploadStream) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockuploadStreamMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockuploadStream)(nil).Context))
}

// Recv mocks base method.
func (m *MockuploadStream) Recv() (*upload.UploadPhotoRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*upload.UploadPhotoRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockuploadStreamMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockuploadStream)(nil).Recv))
}

// SendAndClose mocks base method.
func (m *MockuploadStream) SendAndClose(arg0 *upload.UploadPhotoResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockuploadStreamMockRecorder) SendAndClose(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockuploadStream)(nil).SendAndClose), arg0)
}
