services:

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      # - "5672:5672" # needed for code tests # AMQP
      - "15672:15672"  # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 10


  user_postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matteo -d user_db"]
      interval: 2s
      timeout: 3s
      retries: 10
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: internal/user/Dockerfile.user
    image: user-service:latest
    ports:
      - "8081:8081"
    environment:
      DB_HOST: user_postgres
      DB_USER: matteo
      DB_PASSWORD: password
      DB_NAME_USER: user_db
      DB_PORT_USER: 5432
      USER_GRPC_PORT: 8081
      JWT_SECRET: "?&%:(Hzp@g98••••••••E/O.9.cyW#;m"
    depends_on:
      user_postgres:
        condition: service_healthy # necessary to make the container work


  gallery_postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: matteo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gallery_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matteo -d gallery_db" ]
      interval: 2s
      timeout: 3s
      retries: 10
    volumes:
      - gallery_pgdata:/var/lib/postgresql/data

  gallery-service:
    build:
      context: .
      dockerfile: internal/gallery/Dockerfile.gallery
    image: gallery-service:latest
    ports:
      - "8082:8082"
    environment:
      DB_HOST: gallery_postgres
      DB_USER: matteo
      DB_PASSWORD: password
      DB_NAME_GALLERY: gallery_db
      DB_PORT_GALLERY: 5432
      GALLERY_GRPC_PORT: 8082
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      JWT_SECRET: "?&%:(Hzp@g98••••••••E/O.9.cyW#;m"
    depends_on:
      gallery_postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  upload-service:
    build:
      context: .
      dockerfile: internal/upload/Dockerfile.upload
    image: upload-service:latest
    ports:
      - "8083:8083"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_GRPC_PORT: 8083
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      RABBITMQ_EXCHANGE: gallery.events
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: photos
      MINIO_USE_SSL: false
      GALLERY_SERVICE_ADDRESS: gallery-service:8082
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started


  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped


  notification-service:
    build:
      context: .
      dockerfile: internal/notification/Dockerfile.notification
    image: notification-service:latest
    ports:
      - "8084:8084"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      NOTIFICATION_GRPC_PORT: 8084
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      GALLERY_SERVICE_ADDRESS: gallery-service:8082
    depends_on:
      rabbitmq:
        condition: service_healthy


  gateway:
    build:
      context: .
      dockerfile: internal/handlers/Dockerfile.gateway
    image: gateway:latest
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: 8080
      USER_SERVICE_ADDRESS: user-service:8081
      GALLERY_SERVICE_ADDRESS: gallery-service:8082
      UPLOAD_SERVICE_ADDRESS: upload-service:8083
      NOTIFICATION_SERVICE_ADDRESS: notification-service:8084
    depends_on:
      # to fix
      rabbitmq:
        condition: service_healthy


volumes:
  user_pgdata:
  gallery_pgdata:
  minio-data:

