// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./api/interfaces.go -destination=./mocks/api_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "photogallery/internal/gallery/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// CloseGallery mocks base method.
func (m *MockCommandRunner) CloseGallery(ctx context.Context, galleryID, callerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseGallery", ctx, galleryID, callerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseGallery indicates an expected call of CloseGallery.
func (mr *MockCommandRunnerMockRecorder) CloseGallery(ctx, galleryID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseGallery", reflect.TypeOf((*MockCommandRunner)(nil).CloseGallery), ctx, galleryID, callerID)
}

// CreateGallery mocks base method.
func (m *MockCommandRunner) CreateGallery(ctx context.Context, name, description string, moderatorID uuid.UUID) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGallery", ctx, name, description, moderatorID)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGallery indicates an expected call of CreateGallery.
func (mr *MockCommandRunnerMockRecorder) CreateGallery(ctx, name, description, moderatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGallery", reflect.TypeOf((*MockCommandRunner)(nil).CreateGallery), ctx, name, description, moderatorID)
}

// DeleteGallery mocks base method.
func (m *MockCommandRunner) DeleteGallery(ctx context.Context, galleryID, callerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGallery", ctx, galleryID, callerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGallery indicates an expected call of DeleteGallery.
func (mr *MockCommandRunnerMockRecorder) DeleteGallery(ctx, galleryID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGallery", reflect.TypeOf((*MockCommandRunner)(nil).DeleteGallery), ctx, galleryID, callerID)
}

// JoinGallery mocks base method.
func (m *MockCommandRunner) JoinGallery(ctx context.Context, galleryID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGallery", ctx, galleryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinGallery indicates an expected call of JoinGallery.
func (mr *MockCommandRunnerMockRecorder) JoinGallery(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGallery", reflect.TypeOf((*MockCommandRunner)(nil).JoinGallery), ctx, galleryID, userID)
}

// LeaveGallery mocks base method.
func (m *MockCommandRunner) LeaveGallery(ctx context.Context, galleryID, callerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveGallery", ctx, galleryID, callerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveGallery indicates an expected call of LeaveGallery.
func (mr *MockCommandRunnerMockRecorder) LeaveGallery(ctx, galleryID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveGallery", reflect.TypeOf((*MockCommandRunner)(nil).LeaveGallery), ctx, galleryID, callerID)
}

// SendModeratorAlert mocks base method.
func (m *MockCommandRunner) SendModeratorAlert(ctx context.Context, galleryID, callerID uuid.UUID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendModeratorAlert", ctx, galleryID, callerID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendModeratorAlert indicates an expected call of SendModeratorAlert.
func (mr *MockCommandRunnerMockRecorder) SendModeratorAlert(ctx, galleryID, callerID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendModeratorAlert", reflect.TypeOf((*MockCommandRunner)(nil).SendModeratorAlert), ctx, galleryID, callerID, message)
}

// MockQueryRunner is a mock of QueryRunner interface.
type MockQueryRunner struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRunnerMockRecorder
	isgomock struct{}
}

// MockQueryRunnerMockRecorder is the mock recorder for MockQueryRunner.
type MockQueryRunnerMockRecorder struct {
	mock *MockQueryRunner
}

// NewMockQueryRunner creates a new mock instance.
func NewMockQueryRunner(ctrl *gomock.Controller) *MockQueryRunner {
	mock := &MockQueryRunner{ctrl: ctrl}
	mock.recorder = &MockQueryRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRunner) EXPECT() *MockQueryRunnerMockRecorder {
	return m.recorder
}

// GetGallery mocks base method.
func (m *MockQueryRunner) GetGallery(ctx context.Context, id uuid.UUID) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGallery", ctx, id)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGallery indicates an expected call of GetGallery.
func (mr *MockQueryRunnerMockRecorder) GetGallery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGallery", reflect.TypeOf((*MockQueryRunner)(nil).GetGallery), ctx, id)
}

// IsMember mocks base method.
func (m *MockQueryRunner) IsMember(ctx context.Context, galleryID, userID uuid.UUID) (bool, models.GalleryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, galleryID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(models.GalleryStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsMember indicates an expected call of IsMember.
func (mr *MockQueryRunnerMockRecorder) IsMember(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockQueryRunner)(nil).IsMember), ctx, galleryID, userID)
}

// ListGalleries mocks base method.
func (m *MockQueryRunner) ListGalleries(ctx context.Context, myGalleries bool, callerID uuid.UUID, pageSize int, pageToken string) ([]models.Gallery, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGalleries", ctx, myGalleries, callerID, pageSize, pageToken)
	ret0, _ := ret[0].([]models.Gallery)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGalleries indicates an expected call of ListGalleries.
func (mr *MockQueryRunnerMockRecorder) ListGalleries(ctx, myGalleries, callerID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleries", reflect.TypeOf((*MockQueryRunner)(nil).ListGalleries), ctx, myGalleries, callerID, pageSize, pageToken)
}

// ListGalleriesByMember mocks base method.
func (m *MockQueryRunner) ListGalleriesByMember(ctx context.Context, userID uuid.UUID, pageSize int, pageToken string) ([]models.Gallery, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGalleriesByMember", ctx, userID, pageSize, pageToken)
	ret0, _ := ret[0].([]models.Gallery)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGalleriesByMember indicates an expected call of ListGalleriesByMember.
func (mr *MockQueryRunnerMockRecorder) ListGalleriesByMember(ctx, userID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleriesByMember", reflect.TypeOf((*MockQueryRunner)(nil).ListGalleriesByMember), ctx, userID, pageSize, pageToken)
}

// ListMembers mocks base method.
func (m *MockQueryRunner) ListMembers(ctx context.Context, galleryID uuid.UUID) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, galleryID)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockQueryRunnerMockRecorder) ListMembers(ctx, galleryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockQueryRunner)(nil).ListMembers), ctx, galleryID)
}
