// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/api_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "photogallery/internal/gallery/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockCommandRunner) AddMember(ctx context.Context, galleryID uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, galleryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockCommandRunnerMockRecorder) AddMember(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockCommandRunner)(nil).AddMember), ctx, galleryID, userID)
}

// CloseGallery mocks base method.
func (m *MockCommandRunner) CloseGallery(ctx context.Context, galleryID uuid.UUID, callerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseGallery", ctx, galleryID, callerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseGallery indicates an expected call of CloseGallery.
func (mr *MockCommandRunnerMockRecorder) CloseGallery(ctx, galleryID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseGallery", reflect.TypeOf((*MockCommandRunner)(nil).CloseGallery), ctx, galleryID, callerID)
}

// CreateGallery mocks base method.
func (m *MockCommandRunner) CreateGallery(ctx context.Context, name, description, moderatorID string) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGallery", ctx, name, description, moderatorID)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGallery indicates an expected call of CreateGallery.
func (mr *MockCommandRunnerMockRecorder) CreateGallery(ctx, name, description, moderatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGallery", reflect.TypeOf((*MockCommandRunner)(nil).CreateGallery), ctx, name, description, moderatorID)
}

// RemoveMember mocks base method.
func (m *MockCommandRunner) RemoveMember(ctx context.Context, galleryID uuid.UUID, targetUserID, callerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, galleryID, targetUserID, callerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockCommandRunnerMockRecorder) RemoveMember(ctx, galleryID, targetUserID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockCommandRunner)(nil).RemoveMember), ctx, galleryID, targetUserID, callerID)
}

// SendModeratorAlert mocks base method.
func (m *MockCommandRunner) SendModeratorAlert(ctx context.Context, galleryID uuid.UUID, callerID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendModeratorAlert", ctx, galleryID, callerID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendModeratorAlert indicates an expected call of SendModeratorAlert.
func (mr *MockCommandRunnerMockRecorder) SendModeratorAlert(ctx, galleryID, callerID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendModeratorAlert", reflect.TypeOf((*MockCommandRunner)(nil).SendModeratorAlert), ctx, galleryID, callerID, message)
}

// MockQueryRunner is a mock of QueryRunner interface.
type MockQueryRunner struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRunnerMockRecorder
	isgomock struct{}
}

// MockQueryRunnerMockRecorder is the mock recorder for MockQueryRunner.
type MockQueryRunnerMockRecorder struct {
	mock *MockQueryRunner
}

// NewMockQueryRunner creates a new mock instance.
func NewMockQueryRunner(ctrl *gomock.Controller) *MockQueryRunner {
	mock := &MockQueryRunner{ctrl: ctrl}
	mock.recorder = &MockQueryRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRunner) EXPECT() *MockQueryRunnerMockRecorder {
	return m.recorder
}

// GetGallery mocks base method.
func (m *MockQueryRunner) GetGallery(ctx context.Context, id uuid.UUID) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGallery", ctx, id)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGallery indicates an expected call of GetGallery.
func (mr *MockQueryRunnerMockRecorder) GetGallery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGallery", reflect.TypeOf((*MockQueryRunner)(nil).GetGallery), ctx, id)
}

// ListGalleries mocks base method.
func (m *MockQueryRunner) ListGalleries(ctx context.Context, myGalleries bool, callerID string, pageSize int, pageToken string) ([]models.Gallery, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGalleries", ctx, myGalleries, callerID, pageSize, pageToken)
	ret0, _ := ret[0].([]models.Gallery)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGalleries indicates an expected call of ListGalleries.
func (mr *MockQueryRunnerMockRecorder) ListGalleries(ctx, myGalleries, callerID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleries", reflect.TypeOf((*MockQueryRunner)(nil).ListGalleries), ctx, myGalleries, callerID, pageSize, pageToken)
}

// ListMembers mocks base method.
func (m *MockQueryRunner) ListMembers(ctx context.Context, galleryID uuid.UUID) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, galleryID)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockQueryRunnerMockRecorder) ListMembers(ctx, galleryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockQueryRunner)(nil).ListMembers), ctx, galleryID)
}
