// Code generated by MockGen. DO NOT EDIT.
// Source: ./command/repository.go
//
// Generated by this command:
//
//	mockgen -source=./command/repository.go -destination=./mocks/command_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "photogallery/internal/gallery/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandRepository is a mock of CommandRepository interface.
type MockCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockCommandRepositoryMockRecorder is the mock recorder for MockCommandRepository.
type MockCommandRepositoryMockRecorder struct {
	mock *MockCommandRepository
}

// NewMockCommandRepository creates a new mock instance.
func NewMockCommandRepository(ctrl *gomock.Controller) *MockCommandRepository {
	mock := &MockCommandRepository{ctrl: ctrl}
	mock.recorder = &MockCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRepository) EXPECT() *MockCommandRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCommandRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCommandRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCommandRepository)(nil).Close))
}

// CreateGallery mocks base method.
func (m *MockCommandRepository) CreateGallery(ctx context.Context, g *models.Gallery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGallery", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGallery indicates an expected call of CreateGallery.
func (mr *MockCommandRepositoryMockRecorder) CreateGallery(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGallery", reflect.TypeOf((*MockCommandRepository)(nil).CreateGallery), ctx, g)
}

// DeleteGallery mocks base method.
func (m *MockCommandRepository) DeleteGallery(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGallery", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGallery indicates an expected call of DeleteGallery.
func (mr *MockCommandRepositoryMockRecorder) DeleteGallery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGallery", reflect.TypeOf((*MockCommandRepository)(nil).DeleteGallery), ctx, id)
}

// GetGallery mocks base method.
func (m *MockCommandRepository) GetGallery(ctx context.Context, id uuid.UUID) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGallery", ctx, id)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGallery indicates an expected call of GetGallery.
func (mr *MockCommandRepositoryMockRecorder) GetGallery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGallery", reflect.TypeOf((*MockCommandRepository)(nil).GetGallery), ctx, id)
}

// JoinGallery mocks base method.
func (m *MockCommandRepository) JoinGallery(ctx context.Context, galleryID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGallery", ctx, galleryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinGallery indicates an expected call of JoinGallery.
func (mr *MockCommandRepositoryMockRecorder) JoinGallery(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGallery", reflect.TypeOf((*MockCommandRepository)(nil).JoinGallery), ctx, galleryID, userID)
}

// LeaveGallery mocks base method.
func (m *MockCommandRepository) LeaveGallery(ctx context.Context, galleryID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveGallery", ctx, galleryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveGallery indicates an expected call of LeaveGallery.
func (mr *MockCommandRepositoryMockRecorder) LeaveGallery(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveGallery", reflect.TypeOf((*MockCommandRepository)(nil).LeaveGallery), ctx, galleryID, userID)
}

// UpdateGallery mocks base method.
func (m *MockCommandRepository) UpdateGallery(ctx context.Context, g *models.Gallery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGallery", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGallery indicates an expected call of UpdateGallery.
func (mr *MockCommandRepositoryMockRecorder) UpdateGallery(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGallery", reflect.TypeOf((*MockCommandRepository)(nil).UpdateGallery), ctx, g)
}
