// Code generated by MockGen. DO NOT EDIT.
// Source: ./query/repository.go
//
// Generated by this command:
//
//	mockgen -source=./query/repository.go -destination=./mocks/query_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "photogallery/internal/gallery/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockQueryRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQueryRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQueryRepository)(nil).Close))
}

// GalleryExists mocks base method.
func (m *MockQueryRepository) GalleryExists(arg0 context.Context, arg1 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GalleryExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GalleryExists indicates an expected call of GalleryExists.
func (mr *MockQueryRepositoryMockRecorder) GalleryExists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GalleryExists", reflect.TypeOf((*MockQueryRepository)(nil).GalleryExists), arg0, arg1)
}

// GetGallery mocks base method.
func (m *MockQueryRepository) GetGallery(arg0 context.Context, arg1 uuid.UUID) (*models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGallery", arg0, arg1)
	ret0, _ := ret[0].(*models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGallery indicates an expected call of GetGallery.
func (mr *MockQueryRepositoryMockRecorder) GetGallery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGallery", reflect.TypeOf((*MockQueryRepository)(nil).GetGallery), arg0, arg1)
}

// IsMember mocks base method.
func (m *MockQueryRepository) IsMember(ctx context.Context, galleryID, userID uuid.UUID) (bool, models.GalleryStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, galleryID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(models.GalleryStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsMember indicates an expected call of IsMember.
func (mr *MockQueryRepositoryMockRecorder) IsMember(ctx, galleryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockQueryRepository)(nil).IsMember), ctx, galleryID, userID)
}

// ListGalleries mocks base method.
func (m *MockQueryRepository) ListGalleries(arg0 context.Context, arg1 int, arg2 uuid.UUID) ([]models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGalleries", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGalleries indicates an expected call of ListGalleries.
func (mr *MockQueryRepositoryMockRecorder) ListGalleries(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleries", reflect.TypeOf((*MockQueryRepository)(nil).ListGalleries), arg0, arg1, arg2)
}

// ListGalleriesByMember mocks base method.
func (m *MockQueryRepository) ListGalleriesByMember(ctx context.Context, userID uuid.UUID, limit int, after uuid.UUID) ([]models.Gallery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGalleriesByMember", ctx, userID, limit, after)
	ret0, _ := ret[0].([]models.Gallery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGalleriesByMember indicates an expected call of ListGalleriesByMember.
func (mr *MockQueryRepositoryMockRecorder) ListGalleriesByMember(ctx, userID, limit, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGalleriesByMember", reflect.TypeOf((*MockQueryRepository)(nil).ListGalleriesByMember), ctx, userID, limit, after)
}

// ListMembers mocks base method.
func (m *MockQueryRepository) ListMembers(arg0 context.Context, arg1 uuid.UUID) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", arg0, arg1)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockQueryRepositoryMockRecorder) ListMembers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockQueryRepository)(nil).ListMembers), arg0, arg1)
}
