// Code generated by MockGen. DO NOT EDIT.
// Source: photogallery/gen/notification (interfaces: NotificationService_SubscribeServer)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_notification_stream.go -package=mocks photogallery/gen/notification NotificationService_SubscribeServer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	notification "photogallery/gen/notification"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockNotificationService_SubscribeServer is a mock of NotificationService_SubscribeServer interface.
type MockNotificationService_SubscribeServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationService_SubscribeServerMockRecorder[Res]
	isgomock struct{}
}

// MockNotificationService_SubscribeServerMockRecorder is the mock recorder for MockNotificationService_SubscribeServer.
type MockNotificationService_SubscribeServerMockRecorder[Res any] struct {
	mock *MockNotificationService_SubscribeServer[Res]
}

// NewMockNotificationService_SubscribeServer creates a new mock instance.
func NewMockNotificationService_SubscribeServer[Res any](ctrl *gomock.Controller) *MockNotificationService_SubscribeServer[Res] {
	mock := &MockNotificationService_SubscribeServer[Res]{ctrl: ctrl}
	mock.recorder = &MockNotificationService_SubscribeServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService_SubscribeServer[Res]) EXPECT() *MockNotificationService_SubscribeServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockNotificationService_SubscribeServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockNotificationService_SubscribeServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockNotificationService_SubscribeServer[Res]) Send(arg0 *notification.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockNotificationService_SubscribeServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockNotificationService_SubscribeServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockNotificationService_SubscribeServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockNotificationService_SubscribeServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockNotificationService_SubscribeServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockNotificationService_SubscribeServer[Res])(nil).SetTrailer), arg0)
}
