// Code generated by MockGen. DO NOT EDIT.
// Source: ./consumer.go
//
// Generated by this command:
//
//	mockgen -source=./consumer.go -destination=./mocks/mock_notifier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	notification "photogallery/gen/notification"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mocknotifier is a mock of notifier interface.
type Mocknotifier struct {
	ctrl     *gomock.Controller
	recorder *MocknotifierMockRecorder
	isgomock struct{}
}

// MocknotifierMockRecorder is the mock recorder for Mocknotifier.
type MocknotifierMockRecorder struct {
	mock *Mocknotifier
}

// NewMocknotifier creates a new mock instance.
func NewMocknotifier(ctrl *gomock.Controller) *Mocknotifier {
	mock := &Mocknotifier{ctrl: ctrl}
	mock.recorder = &MocknotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknotifier) EXPECT() *MocknotifierMockRecorder {
	return m.recorder
}

// PublishNotification mocks base method.
func (m *Mocknotifier) PublishNotification(ctx context.Context, n *notification.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishNotification", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishNotification indicates an expected call of PublishNotification.
func (mr *MocknotifierMockRecorder) PublishNotification(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishNotification", reflect.TypeOf((*Mocknotifier)(nil).PublishNotification), ctx, n)
}
